USE [master]
GO
/****** Object:  Database [BasicTest]    Script Date: 11/29/2023 8:55:54 AM ******/
CREATE DATABASE [BasicTest]
GO
ALTER DATABASE [BasicTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BasicTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BasicTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BasicTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BasicTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [BasicTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BasicTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BasicTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BasicTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BasicTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BasicTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BasicTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BasicTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BasicTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BasicTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BasicTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BasicTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BasicTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BasicTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BasicTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BasicTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BasicTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BasicTest] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BasicTest] SET  MULTI_USER 
GO
ALTER DATABASE [BasicTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BasicTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BasicTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BasicTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BasicTest] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BasicTest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BasicTest] SET QUERY_STORE = ON
GO
ALTER DATABASE [BasicTest] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BasicTest]
GO
/****** Object:  Table [dbo].[tEmployee]    Script Date: 11/29/2023 8:55:54 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tEmployee](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL,
	[dob] [date] NULL,
	[phone] [nvarchar](50) NULL,
	[sex] [bit] NULL,
	[salary] [int] NULL,
	[avatar] [varchar](250) NULL,
	[department] [nvarchar](50) NULL,
 CONSTRAINT [PK_tEmployee] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [BasicTest] SET  READ_WRITE 
GO
