USE [master]
GO
/****** Object:  Database [QlXeMay]    Script Date: 11/30/2023 2:30:16 AM ******/
CREATE DATABASE [QlXeMay]

GO
ALTER DATABASE [QlXeMay] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QlXeMay] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QlXeMay] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QlXeMay] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QlXeMay] SET ARITHABORT OFF 
GO
ALTER DATABASE [QlXeMay] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QlXeMay] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QlXeMay] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QlXeMay] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QlXeMay] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QlXeMay] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QlXeMay] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QlXeMay] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QlXeMay] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QlXeMay] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QlXeMay] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QlXeMay] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QlXeMay] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QlXeMay] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QlXeMay] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QlXeMay] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QlXeMay] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QlXeMay] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QlXeMay] SET  MULTI_USER 
GO
ALTER DATABASE [QlXeMay] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QlXeMay] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QlXeMay] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QlXeMay] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QlXeMay] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QlXeMay] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [QlXeMay] SET QUERY_STORE = ON
GO
ALTER DATABASE [QlXeMay] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QlXeMay]
GO
/****** Object:  Table [dbo].[tXemay]    Script Date: 11/30/2023 2:30:16 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tXemay](
	[sokhung] [varchar](50) NULL,
	[somay] [varchar](50) NULL,
	[mamau] [int] NULL,
	[dungtichxilanh] [int] NULL,
	[hangxe] [nvarchar](50) NULL,
	[tenxe] [nvarchar](50) NULL,
	[anh] [varchar](250) NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tXemay] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [QlXeMay] SET  READ_WRITE 
GO
